/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: e10b4fa08847bd61a7984e2c713ea3ca)
interface __BaseEnv_Env {
	ORIGINALS: R2Bucket;
	DB: D1Database;
	HARVEST_QUEUE: Queue;
	ASSETS: Fetcher;
	APP_ORIGIN: string;
	OPENAI_MODEL: string;
	OPENAI_TRANSCRIBE_MODEL: string;
	AI_DAILY_CALL_LIMIT: string;
	AI_MAX_OUTPUT_TOKENS: string;
	AUTH_MODE: string;
	ACCESS_AUD: string;
	ACCESS_TEAM_DOMAIN: string;
	ACCESS_OWNER_EMAIL: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface ProductionEnv {
		ORIGINALS: R2Bucket;
		DB: D1Database;
		HARVEST_QUEUE: Queue;
		ASSETS: Fetcher;
		APP_ORIGIN: string;
		OPENAI_MODEL: string;
		OPENAI_TRANSCRIBE_MODEL: string;
		AI_DAILY_CALL_LIMIT: string;
		AI_MAX_OUTPUT_TOKENS: string;
		AUTH_MODE: string;
		ACCESS_AUD: string;
		ACCESS_TEAM_DOMAIN: string;
		ACCESS_OWNER_EMAIL: string;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ORIGIN" | "OPENAI_MODEL" | "OPENAI_TRANSCRIBE_MODEL" | "AI_DAILY_CALL_LIMIT" | "AI_MAX_OUTPUT_TOKENS" | "AUTH_MODE" | "ACCESS_AUD" | "ACCESS_TEAM_DOMAIN" | "ACCESS_OWNER_EMAIL">> {}
}
