/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 9deb014c5d80bfc0192888204e601ede)
interface __BaseEnv_Env {
	ORIGINALS: R2Bucket;
	DB: D1Database;
	HARVEST_QUEUE: Queue;
	ASSETS: Fetcher;
	APP_ORIGIN: string;
	OPENAI_MODEL: string;
	OPENAI_TRANSCRIBE_MODEL: string;
	AI_DAILY_CALL_LIMIT: string;
	AI_MAX_OUTPUT_TOKENS: string;
	APP_PASSWORD: string;
	OPENAI_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface ProductionEnv {
		ORIGINALS: R2Bucket;
		DB: D1Database;
		HARVEST_QUEUE: Queue;
		ASSETS: Fetcher;
		APP_ORIGIN: string;
		OPENAI_MODEL: string;
		OPENAI_TRANSCRIBE_MODEL: string;
		AI_DAILY_CALL_LIMIT: string;
		AI_MAX_OUTPUT_TOKENS: string;
		APP_PASSWORD: string;
		OPENAI_API_KEY: string;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ORIGIN" | "OPENAI_MODEL" | "OPENAI_TRANSCRIBE_MODEL" | "AI_DAILY_CALL_LIMIT" | "AI_MAX_OUTPUT_TOKENS" | "APP_PASSWORD" | "OPENAI_API_KEY">> {}
}
