ALTER TABLE external_sources ADD COLUMN version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE research_runs ADD COLUMN search_reserved INTEGER NOT NULL DEFAULT 0;
CREATE TABLE external_revisions(id TEXT PRIMARY KEY,capture_id TEXT NOT NULL REFERENCES captures(id) ON DELETE CASCADE,source_id TEXT NOT NULL,version INTEGER NOT NULL,action TEXT NOT NULL,data TEXT NOT NULL,created_at INTEGER NOT NULL);
